require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Lab = require('../models/Lab');
const User = require('../models/User');
const connectDB = require('../config/db');

const labs = [
  { labId:'physics-ohms-law', title:"Ohm's Law", subject:'physics', description:"Verify V = I × R", formula:'V = I × R', difficulty:'easy', tags:['electricity','ncert-class-10'], variables:[{symbol:'V',description:'Voltage (V)'},{symbol:'I',description:'Current (A)'},{symbol:'R',description:'Resistance (Ω)'}], procedure:[{step:1,text:'Set R using slider'},{step:2,text:'Vary V from 1–12 V'},{step:3,text:'Record I = V/R'},{step:4,text:'Plot V vs I — verify linear relationship'}], quizQuestions:[{question:"If voltage doubles, resistance constant, current:",options:["Doubles","Halves","Same","Zero"],correctIndex:0,explanation:"I = V/R. Doubling V doubles I."},{question:"A 12V battery across 4Ω gives current:",options:["1 A","2 A","3 A","4 A"],correctIndex:2,explanation:"I = 12/4 = 3 A."},{question:"V-I graph for ohmic resistor is:",options:["Straight line","Parabola","Exponential","Horizontal"],correctIndex:0,explanation:"V = IR is linear."},{question:"SI unit of resistance:",options:["Ampere","Volt","Ohm (Ω)","Watt"],correctIndex:2,explanation:"Resistance is in Ohms (Ω)."}] },
  { labId:'physics-hooks-law', title:"Hooke's Law", subject:'physics', description:"Verify F = kx", formula:'F = k × x', difficulty:'easy', tags:['mechanics','ncert-class-11'], variables:[{symbol:'F',description:'Force (N)'},{symbol:'k',description:'Spring constant (N/m)'},{symbol:'x',description:'Extension (m)'}], procedure:[{step:1,text:'Hang mass on spring'},{step:2,text:'Record extension x'},{step:3,text:'Plot F vs x — slope = k'},{step:4,text:'Note elastic limit'}], quizQuestions:[{question:"Hooke's Law holds only within:",options:["Max length","Elastic limit","Breaking point","Plastic region"],correctIndex:1,explanation:"Beyond elastic limit, permanent deformation occurs."},{question:"Slope of F vs x graph:",options:["Mass","Acceleration","k","Velocity"],correctIndex:2,explanation:"F = kx, slope = k."},{question:"k = 200 N/m, x = 0.05 m, force:",options:["4000 N","10 N","4 N","200 N"],correctIndex:1,explanation:"F = 200 × 0.05 = 10 N."},{question:"k = 500 N/m, x = 3 cm, PE stored:",options:["0.225 J","0.45 J","15 J","1.5 J"],correctIndex:0,explanation:"PE = ½kx² = ½×500×0.0009 = 0.225 J."}] },
  { labId:'physics-simple-pendulum', title:'Simple Pendulum', subject:'physics', description:"Verify T = 2π√(L/g)", formula:'T = 2π√(L/g)', difficulty:'medium', tags:['oscillation','ncert-class-11'], variables:[{symbol:'T',description:'Period (s)'},{symbol:'L',description:'Length (m)'},{symbol:'g',description:'9.8 m/s²'}], procedure:[{step:1,text:'Set length L'},{step:2,text:'Release from ≤15°'},{step:3,text:'Time 20 oscillations ÷ 20'},{step:4,text:'Plot T² vs L — straight line'}], quizQuestions:[{question:"Period depends on:",options:["Mass of bob","Amplitude","Length","String material"],correctIndex:2,explanation:"T = 2π√(L/g) — only L and g matter."},{question:"Quadrupling L multiplies T by:",options:["4","2","½","¼"],correctIndex:1,explanation:"T ∝ √L, so ×√4 = ×2."},{question:"T² vs L graph is:",options:["Parabola","Hyperbola","Straight line","Exponential"],correctIndex:2,explanation:"T² = (4π²/g)L is linear in L."},{question:"On Moon (g=1.6) pendulum:",options:["Swings faster","Swings slower","Stops","Same"],correctIndex:1,explanation:"Lower g → larger T."}] },
  { labId:'physics-refraction', title:'Refraction of Light', subject:'physics', description:"Verify Snell's Law n₁sinθ₁ = n₂sinθ₂", formula:'n₁ sin θ₁ = n₂ sin θ₂', difficulty:'medium', tags:['optics','ncert-class-10'], variables:[{symbol:'n₁',description:'Air (1.0)'},{symbol:'n₂',description:'Glass (~1.5)'},{symbol:'θ₁',description:'Incidence angle'},{symbol:'θ₂',description:'Refraction angle'}], procedure:[{step:1,text:'Set incidence angle θ₁'},{step:2,text:'Read refraction angle θ₂'},{step:3,text:'Calculate n = sinθ₁/sinθ₂'},{step:4,text:'Verify n is constant ~1.5'}], quizQuestions:[{question:"Light entering glass from air:",options:["Speeds up","Slows down","Same","Stops"],correctIndex:1,explanation:"Higher n → slower speed."},{question:"n = 1.5 means glass speed:",options:["1.5× faster","1.5× slower","Same","Varies"],correctIndex:1,explanation:"v = c/n = c/1.5."},{question:"TIR requires:",options:["θ < critical, rarer→denser","θ > critical, denser→rarer","Any angle","Normal incidence"],correctIndex:1,explanation:"TIR: angle > critical, denser→rarer."},{question:"Critical angle for n=1.5:",options:["90°","41.8°","30°","60°"],correctIndex:1,explanation:"sin(θc) = 1/1.5 = 0.667 → 41.8°."}] },
  { labId:'chemistry-titration', title:'Acid–Base Titration', subject:'chemistry', description:"Determine HCl concentration using NaOH", formula:'HCl + NaOH → NaCl + H₂O', difficulty:'medium', tags:['titration','ncert-class-11'], variables:[{symbol:'M₁V₁',description:'Moles of acid'},{symbol:'M₂V₂',description:'Moles of base'},{symbol:'pH 7',description:'Equivalence point'}], procedure:[{step:1,text:'Fill burette with NaOH'},{step:2,text:'Pipette 20 mL HCl + phenolphthalein'},{step:3,text:'Add NaOH dropwise while swirling'},{step:4,text:'Stop at first pale-pink end point'}], quizQuestions:[{question:"pH of neutral solution at 25°C:",options:["0","7","14","1"],correctIndex:1,explanation:"Neutral: pH = 7."},{question:"Phenolphthalein turns pink in:",options:["Acid","Neutral","Base","Pure water"],correctIndex:2,explanation:"Phenolphthalein: colourless in acid, pink in base."},{question:"At equivalence point HCl+NaOH:",options:["pH<7","pH=7","pH>7","pH=0"],correctIndex:1,explanation:"NaCl+H₂O is neutral."},{question:"25 mL of 0.1 M NaOH, moles HCl:",options:["0.25","0.025","0.0025","2.5"],correctIndex:2,explanation:"n = 0.1 × 0.025 = 0.0025 mol."}] },
  { labId:'chemistry-flame-test', title:'Flame Test', subject:'chemistry', description:"Identify metal ions by flame colour", formula:'Metal ion + heat → characteristic emission', difficulty:'easy', tags:['spectroscopy','ncert-class-11'], variables:[{symbol:'Li⁺',description:'Crimson red'},{symbol:'Na⁺',description:'Intense yellow'},{symbol:'K⁺',description:'Lilac/violet'},{symbol:'Cu²⁺',description:'Blue-green'}], procedure:[{step:1,text:'Clean nichrome wire with HCl'},{step:2,text:'Dip in test solution'},{step:3,text:'Hold in blue Bunsen flame'},{step:4,text:'Record colour'}], quizQuestions:[{question:"Na⁺ flame colour:",options:["Crimson","Intense yellow","Lilac","Blue-green"],correctIndex:1,explanation:"Na⁺ emits at 589 nm — yellow."},{question:"K⁺ flame colour:",options:["Blue-green","Crimson","Lilac/violet","Brick red"],correctIndex:2,explanation:"K⁺ gives lilac/violet."},{question:"Different flame colours are due to:",options:["Melting points","Electron energy level transitions","Different masses","Crystal structure"],correctIndex:1,explanation:"Excited electrons emit characteristic wavelengths when returning to ground state."},{question:"Cu²⁺ flame colour:",options:["Yellow","Crimson","Brick red","Blue-green"],correctIndex:3,explanation:"Cu²⁺ gives blue-green."}] },
  { labId:'chemistry-electrolysis', title:'Electrolysis of Water', subject:'chemistry', description:"Decompose water into H₂ and O₂", formula:'2H₂O → 2H₂ + O₂', difficulty:'medium', tags:['electrochemistry','ncert-class-10'], variables:[{symbol:'Cathode (−)',description:'H₂ gas'},{symbol:'Anode (+)',description:'O₂ gas'}], procedure:[{step:1,text:'Set up voltameter with dilute H₂SO₄'},{step:2,text:'Apply voltage, observe bubbles'},{step:3,text:'Collect gases at each electrode'},{step:4,text:'Verify H₂:O₂ = 2:1'}], quizQuestions:[{question:"H₂ is produced at:",options:["Anode (+)","Cathode (−)","Both","Neither"],correctIndex:1,explanation:"Reduction at cathode: 2H⁺ + 2e⁻ → H₂."},{question:"H₂:O₂ volume ratio:",options:["1:2","2:1","1:1","3:1"],correctIndex:1,explanation:"2H₂O → 2H₂ + O₂ — ratio 2:1."},{question:"H₂SO₄ added to water to:",options:["Change colour","Increase conductivity","Decrease BP","Neutralise"],correctIndex:1,explanation:"Ions carry current."},{question:"At anode during electrolysis:",options:["H₂ produced","O₂ produced","Na deposited","Cl₂ produced"],correctIndex:1,explanation:"Oxidation at anode: 2H₂O → O₂ + 4H⁺ + 4e⁻."}] },
  { labId:'chemistry-salt-analysis', title:'Salt Analysis', subject:'chemistry', description:"Identify cation and anion in unknown salt", formula:'Preliminary → Cation → Anion → Confirmatory', difficulty:'hard', tags:['qualitative-analysis','ncert-class-12'], variables:[{symbol:'CO₃²⁻',description:'CO₂ with HCl'},{symbol:'SO₄²⁻',description:'White ppt BaCl₂'},{symbol:'Cl⁻',description:'White ppt AgNO₃'}], procedure:[{step:1,text:'Physical observations'},{step:2,text:'Flame test'},{step:3,text:'Add HCl — test for carbonates'},{step:4,text:'Anion confirmatory tests'}], quizQuestions:[{question:"White ppt with BaCl₂ insoluble in HCl:",options:["Carbonate","Chloride","Sulphate","Nitrate"],correctIndex:2,explanation:"BaSO₄ — insoluble in HCl confirms SO₄²⁻."},{question:"AgNO₃ white ppt soluble in NH₃:",options:["SO₄²⁻","CO₃²⁻","Cl⁻","NO₃⁻"],correctIndex:2,explanation:"AgCl dissolves in NH₃ — confirms Cl⁻."},{question:"Brown ring test confirms:",options:["Chloride","Sulphate","Nitrate","Carbonate"],correctIndex:2,explanation:"Brown ring = NO₃⁻."},{question:"Blood-red colouration with NH₄SCN:",options:["Fe²⁺","Fe³⁺","Cu²⁺","Zn²⁺"],correctIndex:1,explanation:"[Fe(SCN)₃] blood-red confirms Fe³⁺."}] },
  { labId:'biology-photosynthesis', title:'Rate of Photosynthesis', subject:'biology', description:"Study limiting factors on O₂ production", formula:'6CO₂ + 6H₂O + Light → C₆H₁₂O₆ + 6O₂', difficulty:'medium', tags:['photosynthesis','ncert-class-10'], variables:[{symbol:'I',description:'Light intensity'},{symbol:'[CO₂]',description:'CO₂ concentration'},{symbol:'T',description:'Temperature (°C)'}], procedure:[{step:1,text:'Place Hydrilla in water'},{step:2,text:'Adjust light, record bubbles'},{step:3,text:'Change CO₂ concentration'},{step:4,text:'Change temperature'}], quizQuestions:[{question:"Gas released during photosynthesis:",options:["CO₂","O₂","N₂","H₂"],correctIndex:1,explanation:"O₂ released during photolysis."},{question:"Site of photosynthesis:",options:["Nucleus","Mitochondria","Chloroplast","Vacuole"],correctIndex:2,explanation:"Chloroplasts contain chlorophyll."},{question:"High light but very low CO₂:",options:["Rate doubles","Rate unchanged","Halves","Zero"],correctIndex:1,explanation:"Blackman's Law — CO₂ is limiting factor."},{question:"Optimum temperature:",options:["5–10°C","25–35°C","45–55°C","0°C"],correctIndex:1,explanation:"Enzymes peak at 25–35°C."}] },
  { labId:'biology-osmosis', title:'Osmosis in Plant Cells', subject:'biology', description:"Observe osmosis in potato strips", formula:'Water: low solute → high solute', difficulty:'easy', tags:['osmosis','ncert-class-9'], variables:[{symbol:'[S]',description:'Sucrose conc (%)'},{symbol:'Δm',description:'Mass change'}], procedure:[{step:1,text:'Cut uniform potato strips, weigh'},{step:2,text:'Place in 0–20% sucrose solutions'},{step:3,text:'Wait 30 min, blot, reweigh'},{step:4,text:'Plot % mass change vs [S]'}], quizQuestions:[{question:"Osmosis: water moves from:",options:["High→low solute","Low→high solute","High→low pressure","Equal conc"],correctIndex:1,explanation:"Low solute → high solute (low water potential)."},{question:"Potato in distilled water:",options:["Shrinks","Gains mass","Unchanged","Dissolves"],correctIndex:1,explanation:"Water enters by osmosis — gains mass."},{question:"Plasmolysis occurs when cell:",options:["Gains water","Loses water to hypertonic","Divides","Absorbs glucose"],correctIndex:1,explanation:"Hypertonic → cell loses water → plasmolysis."},{question:"Isotonic solution causes:",options:["Turgidity","Plasmolysis","No net osmosis","Bursting"],correctIndex:2,explanation:"Equal concentration — no net water movement."}] },
  { labId:'biology-mitosis', title:'Stages of Mitosis', subject:'biology', description:"Identify PMAT phases under microscope", formula:'Parent cell (2n) → 2 identical daughter cells (2n)', difficulty:'medium', tags:['cell-division','ncert-class-11'], variables:[{symbol:'P',description:'Prophase'},{symbol:'M',description:'Metaphase'},{symbol:'A',description:'Anaphase'},{symbol:'T',description:'Telophase'}], procedure:[{step:1,text:'Prepare onion root tip squash'},{step:2,text:'Stain with aceto-orcein'},{step:3,text:'Observe at 400× magnification'},{step:4,text:'Identify and sketch PMAT phases'}], quizQuestions:[{question:"Chromosomes at equator during:",options:["Prophase","Anaphase","Metaphase","Telophase"],correctIndex:2,explanation:"Metaphase: chromosomes align at metaphase plate."},{question:"Sister chromatids separate during:",options:["Prophase","Metaphase","Anaphase","Telophase"],correctIndex:2,explanation:"Anaphase: centromeres split."},{question:"Mitosis produces:",options:["4 haploid","2 identical diploid","2 haploid","1 diploid"],correctIndex:1,explanation:"2 genetically identical 2n cells."},{question:"Correct phase order:",options:["MPAT","PMAT","AMPT","TPAM"],correctIndex:1,explanation:"PMAT: Prophase, Metaphase, Anaphase, Telophase."}] },
  { labId:'biology-dna-extraction', title:'DNA Extraction', subject:'biology', description:"Extract visible DNA from banana", formula:'Lysis + Salt + Ethanol → DNA threads', difficulty:'easy', tags:['genetics','ncert-class-12'], variables:[{symbol:'SDS',description:'Detergent — lyses membranes'},{symbol:'NaCl',description:'Salt — neutralises DNA'},{symbol:'EtOH',description:'Cold ethanol — precipitates DNA'}], procedure:[{step:1,text:'Mash banana + salt + detergent'},{step:2,text:'Filter to remove solids'},{step:3,text:'Pour cold ethanol gently over filtrate'},{step:4,text:'Spool DNA threads at interface'}], quizQuestions:[{question:"DNA found primarily in:",options:["Ribosome","Cell membrane","Nucleus & mitochondria","Vacuole"],correctIndex:2,explanation:"Most DNA in nucleus; mitochondria have own DNA."},{question:"SDS (detergent) role:",options:["Cuts DNA","Breaks cell & nuclear membranes","Colours DNA","Dissolves DNA"],correctIndex:1,explanation:"SDS disrupts lipid bilayer."},{question:"Cold ethanol used because:",options:["DNA dissolves in it","DNA precipitates at interface","Only denatures protein","Lyses cells"],correctIndex:1,explanation:"DNA insoluble in ethanol — precipitates as white threads."},{question:"DNA structure:",options:["Single helix","Triple helix","Double helix","Linear chain"],correctIndex:2,explanation:"Watson & Crick 1953: double helix."}] },
  { labId:'mathematics-derivatives', title:'Derivatives & Tangent Lines', subject:'mathematics', description:"Visualise f'(x) as slope of tangent line", formula:"f'(x) = lim[h→0] [f(x+h)−f(x)]/h", difficulty:'medium', tags:['calculus','ncert-class-12'], variables:[{symbol:"f'(x)",description:'Derivative at x'},{symbol:'m',description:'Tangent slope'}], procedure:[{step:1,text:'Select function'},{step:2,text:'Drag x slider'},{step:3,text:'Observe tangent line and slope'},{step:4,text:'Compare with analytical derivative'}], quizQuestions:[{question:"f(x) = x² at x = 3, f'(x) =",options:["9","6","3","2"],correctIndex:1,explanation:"f'(x) = 2x → f'(3) = 6."},{question:"Horizontal tangent means f'(x) is:",options:["Positive","Negative","Zero","Undefined"],correctIndex:2,explanation:"Horizontal tangent → slope = 0."},{question:"d/dx(5) =",options:["5","1","0","x"],correctIndex:2,explanation:"Derivative of constant = 0."},{question:"f'(x) > 0 means f is:",options:["Decreasing","Increasing","Constant","Concave down"],correctIndex:1,explanation:"Positive derivative → increasing function."}] },
  { labId:'cs-logic-gates', title:'Logic Gates Simulator', subject:'computer-science', description:"Build Boolean circuits and verify truth tables", formula:'Y = A·B (AND) | Y = A+B (OR) | Y = Ā (NOT)', difficulty:'easy', tags:['digital-circuits','ncert-cs'], variables:[{symbol:'A,B',description:'Binary inputs'},{symbol:'Y',description:'Output'}], procedure:[{step:1,text:'Select gate type'},{step:2,text:'Toggle inputs A and B'},{step:3,text:'Observe output Y'},{step:4,text:'Verify truth table'}], quizQuestions:[{question:"AND outputs 1 when:",options:["Any input = 1","Both inputs = 1","Both = 0","Any = 0"],correctIndex:1,explanation:"AND: Y = A·B = 1 only when both are 1."},{question:"NOT gate input A=0, output Y=",options:["0","1","Undefined","Voltage"],correctIndex:1,explanation:"NOT inverts: NOT(0) = 1."},{question:"NAND equivalent:",options:["AND then NOT","OR then NOT","Two NOTs","XOR then AND"],correctIndex:0,explanation:"NAND = NOT-AND: universal gate."},{question:"XOR outputs 1 when:",options:["Both = 1","Both = 0","Inputs differ","Inputs equal"],correctIndex:2,explanation:"XOR: A⊕B = 1 when A ≠ B."}] },
];

async function seed() {
  await connectDB();
  await Lab.deleteMany({});
  console.log('🗑  Cleared existing labs');
  const inserted = await Lab.insertMany(labs);
  console.log(`✅  Seeded ${inserted.length} labs`);
  if (!(await User.findOne({ email: 'admin@vlabs.in' }))) {
    await User.create({ name: 'Admin', email: 'admin@vlabs.in', password: 'Admin@1234', role: 'admin', schoolClass: 'Staff' });
    console.log('✅  Admin user: admin@vlabs.in / Admin@1234');
  }
  console.log('\n🌱 Seed complete!');
  process.exit(0);
}

seed().catch(err => { console.error('Seed failed:', err); process.exit(1); });
